version: "3.3"
services:
  mem_consumer:
    image: devjare/memory-consumer:latest
    container_name: mem_consumer
    environment:
      - CHOICE=1
    labels:
      user: devjare
    tty: true
  cpu_consumer:
    image: devjare/cpu-consumer:latest
    container_name: cpu_consumer
    labels:
      user: devjare
    tty: true
  fs_consumer:
    image: devjare/fs-consumer:latest
    container_name: fs_consumer
    labels:
      user: devjare
    tty: true
  net_consumer:
    image: devjare/net-consumer:latest
    container_name: net_consumer
    labels:
      user: devjare
    tty: true

